### ISSUE TITLE
Ability to filter by Priorities on the side panel

### ISSUE THREAD

**Issue by SxMShaDoW** [webkhung/jira_on_steroid#1]
During standup, our team likes to go through the stories by priorities (in the new JIRA these are global and "High","medium", etc and the old JIRA were "P0,P1"). In order to do this, we create a quick filter. It would be great if the plugin could pull that priority dynamically and be able to filter without refreshing the page.

**Comment by webkhung** [comment]
@SxMShaDoW This should be doable and a good idea.  I will take a look at it.

**Comment by webkhung** [comment]
@SxMShaDoW It's added.  Not perfect yet - the priority names should be ordered but it is usable for now.  Let me know if it works for you.

**Comment by SxMShaDoW** [comment]
I don't think it needs to be ordered. I think its fine. Works for me and my team! thanks.
