### ISSUE TITLE
Ability to filter by FixVersions 

### ISSUE THREAD

**Issue by SxMShaDoW** [webkhung/jira_on_steroid#2]
Similar to priority, but also have the ability to filter by fixVersions. I notice you already filter by fixVersion. 

Use case:

My team works on multiple versions within a sprint. We normally create swimlanes for these fixVersions and/or quick filters that we have to change all the time. This unfortunately, causes rework.

Let me know if you are too busy and I can look into forking and creating a pull request. (I would just follow what you did in the previous commit of priorities).

**Comment by webkhung** [comment]
@SxMShaDoW Yes feel free to create a PR!

**Comment by SxMShaDoW** [comment]
Closing this. I verified it on my computer. cool stuff!
