### ISSUE TITLE
Once you have the ability to filter by issuetype. Also be able to "hide" sub-tasks.

### ISSUE THREAD

**Issue by SxMShaDoW** [webkhung/jira_on_steroid#5]
Sub-tasks can flood the screen really quickly. It would be great to quickly hide them. Maybe an option in the filter by issuetype panel.

**Comment by SxMShaDoW** [comment]
Current solution works, but is not scalable right now. Should I leave this open?

**Comment by webkhung** [comment]
@SxMShaDoW 
Actually I think all the subtasks already have this css class added by jira `ghx-issue-subtask`. If that's true, I just need to toggle that class.
